### ISSUE TITLE
Error: s.randomBytes is not a function

### ISSUE THREAD

**Issue by benjick** [thompsonsj/slate-serializers#119]
Hello!

I'm trying to use this library in Next14 (app router), but I'm getting an error: `Error: s.randomBytes is not a function`

This is my code:
```tsx
const node = [{"type":"h3","children":[{"text":"test"}]}]
...
<SlateToReact node={node} />
```

It works if instead input `[{"children":[{"text":"test"}]}]`

Any idea how I can resolve it?

**Comment by frederico-taramaschi** [comment]
I was looking to use this package but I also get this error when using the basic example in the README (https://github.com/thompsonsj/slate-serializers/blob/main/packages/react/README.md)
When using it to serialize italic, bold, ... text or something simple like that it's fine. But when using headers, links, lists (ul), ... I get this error as well.

So at first glance it seems to go wrong when things are nested?

**Comment by thompsonsj** [comment]
Hey! Will take a look. I was distracted upgrading the demo site so that I can test the serializers out in a separate project more easily. Will see if I can reproduce.

**Comment by thompsonsj** [comment]
Managed to recreate the issue and fix.

Using `@slate-serializers/react` [2.1.5](https://www.npmjs.com/package/@slate-serializers/react/v/2.1.5) should resolve the issue.
