### ISSUE TITLE
Supported versions of Slate?

### ISSUE THREAD

**Issue by Slapbox** [thompsonsj/slate-serializers#12]
Hey @thompsonsj, thanks for your work on this package!

I learned about it from your comment here: https://github.com/ianstormtaylor/slate/issues/3899#issuecomment-1327644098

I noticed that the supported versions of Slate are not listed in this repo. I assume it's >0.50.0?

**Comment by thompsonsj** [comment]
Thanks @Slapbox ! It's getting there - starting to get some good results.

Good point, I neglected to add docs on Slate version compatibility. It's >0.50.0 with the caveat that I have only tested using v0.72.8 so far, which is the version they have in https://github.com/payloadcms/payload.
