### ISSUE TITLE
Image tags skipped in htmlToSlate serialization

### ISSUE THREAD

**Issue by th8x** [thompsonsj/slate-serializers#120]
Hi, I'm trying to migrate WordPress content to Payload via the REST API.

When I use `htmlToSlate` to serialize an HTML string, the `<img />` tag is skipped, as shown in the example below.

![Screenshot 2023-11-22 at 12 20 28](https://github.com/thompsonsj/slate-serializers/assets/14269962/30438b21-f387-4e0e-9c4a-4bd62c7cd2c0)

Output: `[ { type: 'h2', align: 'center', children: [Array] } ]`

Is there any configuration I missed?

Thank you.

**Comment by thompsonsj** [comment]
I've been working on a way to add style attribute support in a convenient way. It doesn't support this out of the box due to the fact that each Slate implementation is different, but I am noticing that this is a common request. Will add something to the docs as soon as possible!
