### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by DeVoresyah** [thompsonsj/slate-serializers#142]
Hi @thompsonsj ,
I really appreciate what are you building. It really helps me, especially in my company work. I would like to express my thankful by donating/sponsoring this project

**Comment by thompsonsj** [comment]
That's really kind of you to say!

I set up my sponsorship account at https://github.com/sponsors/thompsonsj.

Your comment made my day! Nice to know all of this work is benefitting other people 😄
