### ISSUE TITLE
Support Image Please

### ISSUE THREAD

**Issue by kartick-weloin** [thompsonsj/slate-serializers#162]
{

"children": [

{
"text": ""
}
],
"relationTo": "media",
"type": "upload",

"value": {
"id": "66fb95df9bf01ecebdb99067",
"filename": "web-directory-search-engine-browser-find-concept-21d6d31c-8d80-4b97-9126-95470adcabfc.jpg",
"mimeType": "image/jpeg",
"filesize": 5000000,
"width": 4786,
"height": 3592,
"focalX": 50,
"focalY": 50,
"createdAt": "2024-10-01T06:25:35.427Z",
"updatedAt": "2024-10-01T06:25:35.427Z",
"url": "https://img.nyc3.cdn.digitaloceanspaces.com/web-directory-search-engine-browser-find-concept-21d6d31c-8d80-4b97-9126-95470adcabfc.jpg"
}
},

This is the image object that i got from slate editor but it not converted to <img/> tag and not shown in converted html.

**Comment by thompsonsj** [comment]
Are you using the provided config for Payload CMS? If not, that would explain why you are not seeing the tag.

i.e.

```ts
import { slateToHtml, payloadSlateToHtmlConfig } from '@slate-serializers/html';

const slate = [
  // slate nodes
];

slateToHtml(slate, payloadSlateToHtmlConfig);
```

Note that this config will convert your node to `<img src="https://img.nyc3.cdn.digitaloceanspaces.com/web-directory-search-engine-browser-find-concept-21d6d31c-8d80-4b97-9126-95470adcabfc.jpg" />`.

You can do a more complex transform. Check out the way the configuration is modified in packages/html/src/lib/serializers/slateToHtml/payload.spec.ts.
