### ISSUE TITLE
Incorrect serialisation for nested elements in HTML 

### ISSUE THREAD

**Issue by NourIM** [thompsonsj/slate-serializers#39]
Hi Team, I'm so grateful for this excellent solution that you have made! It will be a beneficial solution for many people and engineers! However, I've noticed an issue with sterilizing nested elements in HTML. 

Example
`<p><u><em><strong>Our S</strong></em></u><strong>ervi</strong><u><em><strong>ce</strong></em></u><em><strong>s </strong></em><em>A</em><u><em>nd</em></u><u><em><strong> </strong></em></u>Mo<u><em><strong>re</strong></em></u></p>`

the result should look like the browser render 

<img width="338" alt="Screenshot 2023-02-08 at 14 32 07" src="https://user-images.githubusercontent.com/14943545/217559416-2db0739f-cc72-4d24-9c84-71878beeb8c5.png">

but it looks 

<img width="539" alt="Screenshot 2023-02-08 at 14 37 50" src="https://user-images.githubusercontent.com/14943545/217560856-92bdf49e-248f-4576-b3b7-d755e8534c0b.png">

It seems the sterilizer needs to go deep to get all the elements!

**Comment by thompsonsj** [comment]
Thanks @NourIM ! On the case...

**Comment by thompsonsj** [comment]
Hey @NourIM , I have added recursion to the function that parses out text marks such as `em`, `i`, and `strong`.

Added a test for the specific example that you gave.

Could you take a look and see if it is the Slate output you are expecting?

https://github.com/thompsonsj/slate-serializers/blob/0831b75337329afcea77313ef5445d9d8c80d045/__tests__/serializers/htmlToSlate/index.spec.ts#L411-L467

This change is released in version 0.0.27.

**Comment by NourIM** [comment]
@thompsonsj Sorry for the late reply, I confirm the updates fixed the issue! thank you very much :) 
 one more question, does the demo work with the latest version? cause it doesn't seems so!
<img width="1595" alt="Screenshot 2023-02-22 at 22 04 17" src="https://user-images.githubusercontent.com/14943545/220770221-260d8bf0-8644-4902-bb0c-9e204c664637.png">
