### ISSUE TITLE
htmlparser2 dependency unexpected token error

### ISSUE THREAD

**Issue by loeffelr** [thompsonsj/slate-serializers#44]
This seems like a great package and i would love to use it!

Right now i can't install it as it makes problems with dep htmlparser2. Many people reporting this error. I think one possible solution is to downgrade it a few versions.

<img width="1328" alt="Screenshot 2023-02-14 at 18 30 01" src="https://user-images.githubusercontent.com/38214863/218724662-654fe835-43aa-4eb2-b593-430ffd8d4b4a.png">

**Comment by thompsonsj** [comment]
Thanks for bringing this to my attention @loeffelr ! It makes sense to downgrade to the previous version of `htmlparser2`. If you do try it out, let me know if it works now - released in version 0.0.29. Otherwise, post any subsequent errors!

**Comment by loeffelr** [comment]
Thank you, it does work!
