### ISSUE TITLE
Module not found: Can't resolve 'css-select'

### ISSUE THREAD

**Issue by g-wozniak** [thompsonsj/slate-serializers#54]
When attempting to use the package (htmlToSlate()), I am getting execution error. 

```
Module not found: Can't resolve 'css-select'
error - ./node_modules/slate-serializers/lib/serializers/htmlToSlate/index.js:8:21

```

Installing the _css-select_ package manually seems to solve the problem but might be worth to add it as a required dependency.

Thank you for your time working on this package btw.
Appreciate it!

**Comment by thompsonsj** [comment]
Thanks! I noticed that I had `css-select` as a `devDependency`, which is clearly a mistake!

Sorry I got to this so late! I was distracted by other projects 😅
