### ISSUE TITLE
gatherTextMarkAttributes using defaultConfig

### ISSUE THREAD

**Issue by fsuk** [thompsonsj/slate-serializers#76]
[slate-serializers](https://github.com/thompsonsj/slate-serializers/tree/main)/[src](https://github.com/thompsonsj/slate-serializers/tree/main/src)/[serializers](https://github.com/thompsonsj/slate-serializers/tree/main/src/serializers)/[htmlToSlate](https://github.com/thompsonsj/slate-serializers/tree/main/src/serializers/htmlToSlate)/index.ts

Line 85:
Call to gatherTextMarkAttributes is not passing in the config and instead uses the defaultConfig

**Comment by fsuk** [comment]
Pull request submitted to fix issue
#77

**Comment by thompsonsj** [comment]
Merged and released in [version 0.4.1](https://www.npmjs.com/package/slate-serializers/v/0.4.1). Thank you!
